### ISSUE TITLE
Missing Atmosphere link

### ISSUE THREAD

**Issue by SachaG** [datariot/meteor-ganalytics#16]
For some reason the Atmosphere repo doesn't link back to this package's GitHub page?

https://atmospherejs.com/datariot/ganalytics

**Comment by dandv** [comment]
https://atmospherejs.com/datariot/ganalytics points to https://github.com/datariot/meteor-ganalytics/

**Comment by datariot** [comment]
I think I fixed this a while ago. Thanks!
